# Generated by Django 4.1.3 on 2022-11-19 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_questions_hint_label_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
