# Generated by Django 6.0 on 2025-12-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_journalentry_is_bookmarked'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='json_content',
            field=models.JSONField(null=True),
        ),
    ]
